---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    doc_root: "/var/www/html"

  tasks:
    - name: Install Apache Packages
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"

    - name: Start Apache Service
      service: name=httpd state=started enabled=True
      when: ansible_os_family == "RedHat"

    - name: Install Apache Packages on Ubuntu
      apt: name=apache2 state=present
      when: ansible_os_family == "Debian"

    - name: Start Apache Service
      service: name=apache2 state=started enabled=True
      when: ansible_os_family == "Debian"
   
    - name: Deploy Sample Sites Files
      template: src=templates/index.j2 dest=/var/www/html/index.html
      notify: 
      - Restart Apache
  
    - name: Deploy Sample Sites Files
      template: src=templates/info.j2 dest=/var/www/html/info.html

    - name: Start Java Service 
      apt: name=openjdk-8-jdk state=present

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
